# Generated by Django 4.0.6 on 2022-09-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_comment_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
