# Generated by Django 4.0.6 on 2022-08-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_blog_blog_image_alter_blog_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='blog-images/'),
        ),
    ]
